version: "3.8"

services:
  redis:
    image: redis:5
    ports:
      - 6379:6379
  daphne:
    container_name: birdnest-daphne
    build:
      context: ./backend
      dockerfile: Dockerfile.daphne
    depends_on:
      - redis
    env_file:
      - ./backend/backend/.env
    ports:
      - 8001:8001
  gunicorn:
    container_name: birdnest-gunicorn
    build:
      context: ./backend
      dockerfile: Dockerfile.gunicorn
    depends_on:
      - redis
    env_file:
      - ./backend/backend/.env
    ports:
      - 8000:8000
  pilot_broadcast:
    container_name: birdnest-broadcaster
    build:
      context: ./backend
      dockerfile: Dockerfile.broadcaster
    depends_on:
      - redis
      - daphne
      - gunicorn
    env_file:
      - ./backend/backend/.env
  frontend:
    container_name: birdnest-frontend
    build:
      context: ./frontend
    depends_on:
      - daphne
      - gunicorn
    env_file:
      - ./frontend/.env.production
    ports:
      - 3000:3000