version: "3.8"

services:
  postgres:
    image: 527113104203.dkr.ecr.eu-north-1.amazonaws.com/birdnest-postgres
    restart: always
    ports:
      - 5432:5432
  redis:
    image: redis:5
    ports:
      - 6379:6379
  daphne:
    image: 527113104203.dkr.ecr.eu-north-1.amazonaws.com/birdnest-daphne
    container_name: birdnest-daphne
    depends_on:
      - redis
      - postgres
    environment:
      - DJANGO_PRODUCTION=${DJANGO_PRODUCTION}
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - 8001:8001
  gunicorn:
    image: 527113104203.dkr.ecr.eu-north-1.amazonaws.com/birdnest-gunicorn
    container_name: birdnest-gunicorn
    depends_on:
      - redis
      - postgres
    environment:
      - DJANGO_PRODUCTION=true
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - 8000:8000
  pilot_broadcast:
    image: 527113104203.dkr.ecr.eu-north-1.amazonaws.com/birdnest-broadcaster
    container_name: birdnest-broadcaster
    depends_on:
      - redis
      - daphne
      - gunicorn
      - postgres
    environment:
      - DJANGO_PRODUCTION=${DJANGO_PRODUCTION}
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
  frontend:
    image: 527113104203.dkr.ecr.eu-north-1.amazonaws.com/birdnest-frontend
    container_name: birdnest-frontend
    depends_on:
      - daphne
      - gunicorn
    ports:
      - 3000:3000