# Generated by Django 4.1.5 on 2023-01-04 14:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birdnest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='closest_distance',
            field=models.FloatField(default=100000),
        ),
        migrations.AddField(
            model_name='pilot',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='createdDt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('mac', models.CharField(max_length=100)),
                ('ipv4', models.CharField(max_length=100)),
                ('ipv6', models.CharField(max_length=100)),
                ('firmware', models.CharField(max_length=100)),
                ('positionY', models.FloatField()),
                ('positionX', models.FloatField()),
                ('altitude', models.FloatField()),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birdnest.pilot')),
            ],
            options={
                'db_table': 'drones',
            },
        ),
    ]
