# Generated by Django 4.1.5 on 2023-01-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdnest', '0002_pilot_closest_distance_pilot_last_seen_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pilot',
            options={'ordering': ['last_seen']},
        ),
        migrations.AddField(
            model_name='pilot',
            name='drone_serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Drone',
        ),
    ]
